### ISSUE TITLE
zeebe helm does not work on openshift

### ISSUE THREAD

**Issue by milanhorvath** [zeebe-io/zeebe-helm#11]
Hi i have tried to install zeebe-full on openshift environment but i got following error:
[FATAL tini (6)] exec /usr/local/bin/startup.sh failed: Permission denied
Has somebody tried it already on openshift enviroment?

**Comment by salaboy** [comment]
Hi @milanhorvath that rings some bells.. we are not actively testing on Openshift but it will be great to support it, so we appreciate your report. 
It sounds like Openshift needs to you authorize Zeebe containers for privileged use, as there might be some security constraints stopping Zeebe containers to start. I know that Openshift distributions are way more strict than cloud providers, so you might need to relax those configurations or find a way to allow the container to run the startup.sh script.

**Comment by andrejpetras** [comment]
Hi @salaboy, do you have plans to support OpenShift? That would be interesting for us

**Comment by salaboy** [comment]
@andrejpetras this is a community project.. but yeah.. totally.. I think that the problem reported by @milanhorvath is just privileged containers that can get working by configuring OpenShift correctly. Just to be clear.. by `support` I mean that Helm charts run inside OpenShift, did you mean the same?

**Comment by salaboy** [comment]
for reference: https://github.com/zeebe-io/zeebe/issues/3584

**Comment by andrejpetras** [comment]
@salaboy yes, thank you for your prompt action.

**Comment by milanhorvath** [comment]
> I mean that Helm charts run inside OpenShift, did you mean the same?

Hi @salaboy yes. it would be great if the dockerimage can be updated to be run as non root user as this should then help to run it under openshift environment as it is more restrictive on users and groups. Thanks for opening the issue

**Comment by salaboy** [comment]
@milanhorvath @andrejpetras Guys, can you please try with this docker image: `camunda/zeebe:0.23.1-non-root`  in Openshift? 

If you can please let me know how it goes.. so we make that image the default one.

**Comment by salaboy** [comment]
@milanhorvath @andrejpetras did you guys managed to give that a try? Also it is kinda important to let us know which version of openshift are you using? or which ones we should support? I think that between 3 and 4 are big differences, and supporting both is double the work.

**Comment by milanhorvath** [comment]
@salaboy i will try to do the evaluation of the new image today. We are using openshift 4.2.0
Will let you know when i have som new info

**Comment by salaboy** [comment]
@milanhorvath I would love to see which commands are you running and what values file are you using.. if you are using one.. so I can try to reproduce the problem.

**Comment by milanhorvath** [comment]
@salaboy i was able to deploy the non-root image to openshift and deploy a process there.
i have used these two commands
`helm install zeebe-cluster zeebe/zeebe-cluster -n zeebe -f zeebe-cluster.yaml`
`helm install zeebe-operate zeebe/zeebe-operate -n zeebe -f zeebe-operate.yaml`
zeebe-cluster.yaml
i had to change the file extension of the files to txt as otherwise i was not able to append it

[zeebe-cluster.txt](https://github.com/zeebe-io/zeebe-helm/files/4627204/zeebe-cluster.txt)
[zeebe-operate.txt](https://github.com/zeebe-io/zeebe-helm/files/4627206/zeebe-operate.txt)

**Comment by milanhorvath** [comment]
I have also seen another issue regarding the zeebe-operate helm chart. not sure if i should open another issue or i can write it here. The issue is that the resource part from the values.yaml is not taken as it is hardcoded in the deployment.yaml

**Comment by salaboy** [comment]
@milanhorvath please create the issue for operate in the operate chart repository.
Also.. which ElasticSearch version are you using? are you using the provided one with the charts?

I am looking at your values file, but I still don't know which version of openshift are you using.

**Comment by salaboy** [comment]
@milanhorvath can you please share the logs for the brokers when you install the zeebe-cluster helm chart with those values? so I can understand what is going on.

**Comment by milanhorvath** [comment]
@salaboy ok i used the standard helm charts from zeebe helm repo (https://helm.zeebe.io) like is written in documentation. i made the test on openshift 4.2. We are now upgrading to openshift to version 4.4.3 so till end of the week i will also try it there.
But now it is working so everything is OK. do you still need the logs?

**Comment by salaboy** [comment]
if it is working in Openshift 4.x we can closet this.. and mention in the docs that Openshift 3.x is not supported.

**Comment by milanhorvath** [comment]
ok i will close this issue and you will update the docs
