### ISSUE TITLE
Zeebe helm charts broken because helm.zeebe.io is gone

### ISSUE THREAD

**Issue by josh-swayed** [zeebe-io/zeebe-helm#14]
zeebe.helm.io is now showing a GitHub 404 error page

This is preventing any Helm deploys

**Comment by salaboy** [comment]
We are moving to the helm.Camunda.io domain, can you please check that one?

**Comment by josh-swayed** [comment]
Yes it works.

However since helm.zeebe.io is in a lot of documentation you might want to setup a redirect.

**Comment by salaboy** [comment]
I will start changing the docs soon
