### ISSUE TITLE
Update docs to Helm 3.0

### ISSUE THREAD

**Issue by gitizenme** [zeebe-io/zeebe-helm#7]
Current documentation reflects Helm 2.x, for example:

`helm init --service-account helm --upgrade`

The `init` command does not exist in Helm 3.0 as Tiller has been removed from Helm. 

`helm install --name <RELEASE NAME> zeebe/zeebe-full`

The `--name` parameter is removed and `<RELEASE NAME>` is a required argument.  

Link to current docs:
https://docs.zeebe.io/kubernetes/installing-helm.html#initializing-helm-in-your-cluster

**Comment by salaboy** [comment]
@gitizenme this is great.. can you send a PR to do the docs? 
It is highly appreciated to have this changes coming from community users.. 
These charts were written for Helm 2 but testing with Helm 3 is great!

**Comment by salaboy** [comment]
@gitizenme I've tested with Helm3 around Xmas time and it all worked correctly... I will add a note to the docs to make sure that we ask to run the tiller step only if you are on Helm 2

**Comment by salaboy** [comment]
updated
